### ISSUE TITLE
create symfony project in cloned repository

### ISSUE THREAD

**Issue by fredericmineur** [iobis/small-data#1]
I have cloned the repository and then tried to create the symfony project in the same folder....
![image](https://user-images.githubusercontent.com/15698059/40691641-e5e5bb4a-63a4-11e8-9540-d9b9a66d0ed0.png)
InvalidArgumentException
1/should I create the symfony project in another folder?
2/should I clone the repository after creating the symfony project?

**Comment by pieterprovoost** [comment]
Go into the `small-data` directory before generating the project. This should create a subfolder which is also called `small-data`.

**Comment by fredericmineur** [comment]
Thanks Pieter !
