### ISSUE TITLE
cannot create the symfony project from the server

### ISSUE THREAD

**Issue by fredericmineur** [iobis/small-data#2]
![image](https://user-images.githubusercontent.com/15698059/41207771-1b09b03e-6d13-11e8-854c-1b1fd0f781b1.png)
php version: 7.2.5

**Comment by pieterprovoost** [comment]
I increased RAM to 2 GB, can you check if this is better?

**Comment by fredericmineur** [comment]
![image](https://user-images.githubusercontent.com/15698059/41232484-6d0c3314-6d7e-11e8-8943-5f2d825906ec.png)
thanks Pieter
That seemed to be part of the problem...but not only...I'm going to do some more fiddling

**Comment by fredericmineur** [comment]
sorted
