### ISSUE TITLE
connection pgadmin to server

### ISSUE THREAD

**Issue by fredericmineur** [iobis/small-data#3]
I'm trying to follow the instruction to connect pgadmin to the server
https://www.youtube.com/watch?v=zujeb8VWncI
https://www.mozmorris.com/2011/11/15/configure-postgresql-to-accept-tcpip-connections.html

-In  /etc/postgresql/9.5/main, I edited the file pg_hba.conf to have my computer IP address, by adding the following line at the end of the file (with my computer IP address):
"host  all  all  192.168.1.217/32   trust"
-In the file  postgresql.conf, I uncommented the line to listen_addresses, and change "localhost" to "*"
-restarted posgresql (service postgresql restart)
I got this message from pgadmin

![image](https://user-images.githubusercontent.com/15698059/41364291-3565a54c-6f2e-11e8-9a62-c1c38d64115f.png)

I also tried https://www.digitalocean.com/community/questions/remote-access-to-postgresql-with-pgadmin
# ufw allow 5432/tcp

According to 
https://www.digitalocean.com/community/tutorials/how-to-use-nmap-to-scan-for-open-ports-on-your-vps
I checked the open ports
# sudo netstat -plunt 
It shows 1130/postgres, I therefore put 1130 in pgadmin and gave the same error

During everything, I had deconnected the local host from pgadmin.

**Comment by samuelbosch** [comment]
You're trying to connect to a PostgreSQL 9.5 with a pgAdmin 4 which is not compatible. You should have installed Postgres 10 on the server. For the pg_hba, I'd need to have a look.

To install PostgreSQL 10 see https://gist.github.com/alistairewj/8aaea0261fe4015333ddf8bed5fe91f8

**Comment by fredericmineur** [comment]
done
