### ISSUE TITLE
First draft skeleton version of "small data"

### ISSUE THREAD

**Issue by fredericmineur** [iobis/small-data#4]
Hello Pieter,
Could you see if you can make it work on your local machine, so we can discuss about it (maybe on skype).
I believe the steps for you are :
Configuration of the database:
-In the .env file (DATABASE_URL declaration with user and password
-In the config/packages/doctrine.yaml (the present settings are working fine on my machine)
-Create the database by running "php bin/console doctrine:database:create"
-Run the migration of the database with "php bin/console doctrine:migrations:migrate" (it runs the sql migrations files that are already there).
-Load the fixtures to generate dummy data ("php bin/console doctrine:fixtures:load")
(NB maybe you have to run "composer require orm-fixtures –dev" beforehand).
-Open the website on localhost:8000 ("composer require server --dev" and ""php bin/console server:run").
Let me know if it works.
All the best,
Fred

**Comment by pieterprovoost** [comment]
Sorry for the delay. I would probably be best if you document the installation in `README.md`. After setting up PHP, Composer, etc I seem to have some issues with Doctrine. I'll need to look into it later.

```
small-data pieter$ php bin/console doctrine:database:create
Created database "smalldata" for connection named default
small-data pieter$ php bin/console doctrine:migrations:migrate

                    Application Migrations

WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
Migrating up to 20180801204956 from 0

  ++ migrating 20180731130247

     -> ALTER SEQUENCE species_id_seq INCREMENT BY 1
Migration 20180731130247 failed during Execution. Error An exception occurred while executing 'ALTER SEQUENCE species_id_seq INCREMENT BY 1':

SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "species_id_seq" does not exist

In AbstractPostgreSQLDriver.php line 83:

  An exception occurred while executing 'ALTER SEQUENCE species_id_seq INCREMENT BY 1':

  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "species_id_seq" does not exist

In PDOConnection.php line 109:

  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "species_id_seq" does not exist

In PDOConnection.php line 107:

  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "species_id_seq" does not exist

doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]
```

**Comment by fredericmineur** [comment]
Then you should delete all the migration files in src/Migrations   (as well as any table that may have been created in the database in postgresql). 
Maybe check this "https://stackoverflow.com/questions/43606990/clear-list-of-unavailable-migrations-symfony-3" for a complete clean (but that may be optional)(I'm also on Symfony 4).

Then generate a new migration file ("php bin/console make:migration"). This one will normally automatically take all the information in one go from the Entity files (located in src/Entity).

Then run "php bin/console doctrine:migrations:migrate"

If it doesn't work, no worries yet. I'll try to do that on my side and fiddle with it.

**Comment by fredericmineur** [comment]
I created a readme file with all the instructions. Removing manually the migration files should be enough (I have done it many times now).
Don't forget to install the faker (see instructions in readme) before loading the fixture.

**Comment by pieterprovoost** [comment]
It's running now, thanks. I also cleaned up the README a little bit. I have a few urgent things to attend to, but @samuelbosch should be available mid next week.
