### ISSUE TITLE
Problem with one map rendering

### ISSUE THREAD

**Issue by fredericmineur** [iobis/small-data#6]
Hi Samuel, could you look at the last version of the website (I think I didn't make any change to the entities...so you may just have to run only  php bin/console doctrine:fixtures:load)
Can you check the map of occurrences for Sargassum muticum....that one only is not rendered on my machine....the browser console say it is a problem with the API key....maybe it is something to do with the high number of markers....
https://stackoverflow.com/questions/17177390/is-there-any-limit-to-number-of-markers-that-can-be-placed-on-google-static-maps

**Comment by pieterprovoost** [comment]
@fredericmineur Check out https://leafletjs.com/examples.html, you'll have a lot more flexibility.

**Comment by fredericmineur** [comment]
Errors were mostly due to some weird fields in the csv file (those were not easy to spot).
I nevertheless switched to leaflet for all maps
cheers
Fred
